#
# WorldGuardInteractExt configuration file
#
# WARNING: This file is based on WorldGuard region configuration.
#          A single mistyped character can corrupt the file.
#          If WorldGuardInteractExt is unable to parse the file, your configuration
#          will fail to load and the contents of this file will ignored.
#          Please use a YAML validator such as http://yaml-online-parser.appspot.com (for smaller files).
#
# REMEMBER TO KEEP PERIODICAL BACKUPS.
#
# AIR is used when user has no item into his hand
# If action is not possible by Minecraft, even you put material, it will not work!
# Example, for __CAMPFIRE__, if you put AIR into extinguish, you will not able to extinguish fire with hand without any tools.

# Will display log while block interaction, make more easy to debug and configure
# By default verbose log is false
enable_verbose_logs: true
items:
  [
    {
      type: "__CAMPFIRE__",
      # name : should be Flammable / Burnable
      names: ["CAMPFIRE", "SOUL_CAMPFIRE"],
      # Region : you MUST add world name before region name to make it work
      # Put  [] to accept all regions
      # regions: ["myworld.region_1", "myworld.region_2"],
      regions: [], # All regions
      inflame: ["FLINT_AND_STEEL", "FIRE_CHARGE"],
      extinguish: [".+_SHOVEL"],
    }
  ]