name: WorldGuardInteractExt
version: 4.1
main: fr.feneck91.worldguardinteractext.WorldGuardInteractExt
api-version: 1.20
depend: [WorldGuard]
commands:
  wgi:
    description: Main commands for WorldGuardInteractExt plugin
    usage: /wgi <reload|materials>
    permission: wgiext.command
    permission-message: You do not have permission to use this command.
    aliases: [ wgiext ]

permissions:
  wgiext.command:
    description: Use the plugin commands
    default: op
    children:
      wgiext.command.reload: true
      wgiext.command.materials: true

  wgiext.command.reload:
    description: Reload the configuration file.
    permission-message: You do not have permission to use this command.
    default: op

  wgiext.command.materials:
    description: Display all materials for __CAMPFIRE__, __LECTERN__.
    permission-message: You do not have permission to use this command.
    default: op
